language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl
    - LISP=clisp
    - LISP=allegro

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

script:
  - cl -l ironclad -l ironclad-tests
       -e '(setf *debugger-hook*
                 (lambda (&rest ignorable)
                   (declare (ignore ignorable))
                   (uiop:quit -1)))'
       -e '(unless (rt:do-tests) (uiop:quit -1))'
